services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: my_catalog_db
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pgadmin_data:
